### ISSUE TITLE
What is the difference between file upload using S3Transfer vs  put?

### ISSUE THREAD

**Issue by scheung38** [thanhson1085/python-s3#1]
Your article mentioned:

https://sonnguyen.ws/upload-and-download-files-from-aws-s3-with-python-3/

```
transfer = S3Transfer(boto3.client('s3', cfg.AWS_REGION, aws_access_key_id=cfg.AWS_APP_ID,
 aws_secret_access_key=cfg.AWS_APP_SECRET))

transfer.upload_file(file_path, AWS_BUCKET, file_path)
```

How is that different from :

```
s3.Object(AWS_BUCKET, fileName)).put(Body='hello reinvent!')
```

They both do the same thing of uploading to S3 correct? Is it the case of 'transfer' handling the file as well as the path, whereas 'put' only handles a single file name? 

For the case of 'transfer' why is the file_path even repeated twice in the argument list?

**Comment by thanhson1085** [comment]
I am not sure about `put`.
In `transfer.upload_file` we need 3 parameters, the first one is the file path, the second one is bucket name, and the last one is the key. And you have to know the key if you want to download that file

**Comment by scheung38** [comment]
Thanks, 
filepath is filepath for the first argument, 
filepath is key for the second argument

a bit confusing having same name for different meanings? is that possible?

or is it
filepath is filepath for first argument
filepath is fileName for second argument? 

If that's the case then should be

filepath is filepath for first argument
fileName is fileName for second argument? then they cannot be the same correct?

**Comment by thanhson1085** [comment]
That is possible to use file_path for the both (key and file path parameter)
